- name: Add DBeaver GPG apt Key
  apt_key:
    url: '{{ dbs_dbeaver_gpg_key }}'
    state: present

- name: Add DBeaver Repository
  apt_repository:
    repo: 'deb {{ dbs_dbeaver_repo_url }} /'
    state: present

- name: Add Docker GPG apt Key
  apt_key:
    url: '{{ dbs_docker_gpg_key }}'
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: 'deb {{ dbs_docker_repo_url }}'
    state: present
    mode: "0777"

- name: Install MySQL workbench, DBeaver, Python-pip and Docker
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - '{{ dbs_dbms_packages }}'
    - '{{ dbs_docker_packages }}'
    - python-pip

- name: Install Docker Modules for Python
  pip:
    name:
      - docker
    executable: pip

- name: Add vagrant user to Docker groups
  user:
    name: vagrant
    groups: docker
    
- name: Restart docker service
  service:
    name: docker
    state: restarted

- name: Create mariaDB container
  docker_container:
    name: mysqldb
    image: mariadb
    state: started
    ports:
      - '3306:3306'
    env:
      MYSQL_ROOT_PASSWORD: '{{ dbs_mysql_password }}'

- name: Create PostgreSQL container
  docker_container:
    name: postgresdb
    image: postgres
    state: started
    ports:
      - '5432:5432'
    env:
     POSTGRES_PASSWORD: '{{ dbs_postgres_password }}'

- name: Create Microsoft SQL Server container
  docker_container:
    name: mssqldb
    image: mcr.microsoft.com/mssql/server
    state: started
    ports:
      - '1433:1433'
    env:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: '{{ dbs_mssql_password }}'
      MSSQL_PID: "Developer"

- name: Create phpMyAdmin container
  docker_container:
    name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    state: started
    ports:
      - '8081:80'
    links:
      - 'mysqldb:db'

- name: Create PHP/Apache container
  docker_container:
    name: webserver
    image: 'php:apache'
    state: started
    ports:
      - '80:80'
    # volumes:
    # - '/vagrant/olods/dbs/web/:/var/www/html/'
    links:
      - 'mysqldb:db'
