- name: Install Java JDK, JRE and Git
  package:
    name: '{{ item }}'
    state: present
  with_items: '{{ oosd_packages }}'

- name: Install Eclipse IDE
  snap:
    name:
      - eclipse
    classic: yes
    state: present

- name: Execute SceneBuilder installer
  apt:
    deb: '{{ oosd_scenebuilder_url }}'
      
- stat: >-
    path=/home/vagrant/visualparadigm.tar.gz
  register: VisualParadigm_tar

- name: Download Visual Paradigm compressed archive
  get_url:
    url: '{{ oosd_visualparadigm_url }}'
    dest: /home/vagrant/visualparadigm.tar.gz
    mode: "0777"
  when: not VisualParadigm_tar.stat.exists

# - name: Create Visual Paradigm temporary folder
#   file:
#     path: /home/vagrant/visualparadigm
#     state: directory
#     mode: "0777"
#     recurse: true

- name: Unzip Visual Paradigm archive
  unarchive:
    src: >-
      /home/vagrant/visualparadigm.tar.gz
    dest: /home/vagrant/
    remote_src: true
  when: not VisualParadigm_tar.stat.exists

- stat: path=/usr/bin/visualparadigm
  register: visualparadigm_correctlocation

- name: Create Visual Paradigm folder
  file:
    path: /usr/bin/visualparadigm
    state: directory
    mode: "0777"
    recurse: true
  when: not visualparadigm_correctlocation.stat.exists

- name: Move Visual Paradigm to the correct location
  shell:
    cmd: mv /home/vagrant/{{ oosd_visualparadigm_version }} /usr/bin/visualparadigm
  when: not visualparadigm_correctlocation.stat.exists

- name: Ansible create file with content example
  copy:
    dest: /usr/share/applications/visualparadigm.desktop
    content: >
      [Desktop Entry]

      NotShowIn=Unity;

      Name=Visual Paradigm

      Comment=UML Modelling

      Keywords=visual;paradigm;

      Exec=/usr/bin/visualparadigm/{{ oosd_visualparadigm_version }}/Visual_Paradigm

      # Translators: Do NOT translate or transliterate this text (this is an
      icon file name)!

      Icon=/usr/bin/visualparadigm/{{ oosd_visualparadigm_version }}/Application/resources/vpuml.png

      Terminal=false

      Type=Application

      StartupNotify=true
    mode: "0777"
      
- name: Test VisualParadigm
  shell:
    cmd: sudo /usr/bin/visualparadigm/{{ oosd_visualparadigm_version }}/Visual_Paradigm
