 
  - name: Check admin.conf file exists.
    stat:
      path: /etc/kubernetes/admin.conf
    register: k8s_conf

  - name: Initialize the Kubernetes cluster using kubeadm
    command: kubeadm init  --pod-network-cidr=192.168.56.0/24 --apiserver-advertise-address="{{ ansible_enp0s8.ipv4.address }}" --apiserver-cert-extra-sans="{{ ansible_enp0s8.ipv4.address }}"  --node-name k8s-master
    when: not k8s_conf.stat.exists 

  - name: Setup kubeconfig for vagrant user
    command: "{{ item }}"
    with_items:
     - mkdir -p /home/vagrant/.kube
     - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
     - chown vagrant:vagrant /home/vagrant/.kube/config
    when: not k8s_conf.stat.exists 

  - name: Install Weave Net pod network
    become: false
    command: kubectl apply -f "{{ ops_weave_url }}"
    when: not k8s_conf.stat.exists 

  - name: Generate join command
    command: kubeadm token create --print-join-command
    register: join_command
 

  - name: Copy join command to local file
    copy: content="{{ join_command.stdout_lines[0] }}" dest="/vagrant/ansible/join-command"

