- name: Add Docker GPG apt Key
  apt_key:
    url: '{{ ops_docker_gpg_key }}'
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: 'deb {{ ops_docker_repo_url }}'
    state: present
    mode: '0777'

- name: Add Kubernetes GPG apt Key
  apt_key:
    url: '{{ ops_kubernetes_gpg_key }}'
    state: present

- name: Add Kubernetes Repository
  apt_repository:
    repo: 'deb {{ ops_kubernetes_repo_url }}'
    state: present
    mode: '0777'

- name: Install Docker Engine, Python-pip and Kubernetes
  package:
    name:  '{{ item }}'
    state: present
  with_items:
    - '{{ ops_docker_packages }}'
    - python-pip
    - '{{ ops_kubernetes_packages }}'

- name: Install Docker Modules for Python
  pip:
    name: 
      - docker
    executable: pip

- name: Add vagrant user to Docker groups
  user:
    name: vagrant
    groups: docker

- name: restart docker service
  service:
    name: docker
    state: restarted

- name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
  shell: 
    cmd: 'swapoff -a'

- name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Configure node ip
  lineinfile:
    path: /etc/default/kubelet
    line: KUBELET_EXTRA_ARGS=--node-ip={{ ops_master_ip }}
    create: true
    mode: '0777'

- name: Restart kubelet
  service:
    name: kubelet
    state: restarted
