- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
    mode: '0777'

- name: Install Docker Engine
  apt:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Install pip
  apt:
    name: python-pip
    state: present

- name: Install Docker Modules for Python
  pip:
    name: 
      - docker
      # - docker-py
    executable: pip
- name: Add vagrant user to Docker groups
  user:
    name: vagrant
    groups: docker

- name: restart docker service
  service:
    name: docker
    state: restarted

- name: Add Kubernetes GPG apt Key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add Kubernetes Repository
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    mode: '0777'

- name: Install Kubernetes
  apt:
    name: 
      - kubeadm
      - kubelet
      - kubectl
    state: present

- name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
  shell: |
    swapoff -a

- name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Configure node ip
  lineinfile:
    path: /etc/default/kubelet
    line: KUBELET_EXTRA_ARGS=--node-ip={{ ansible_enp0s8.ipv4.address }}
    create: true
    mode: '0777'

- name: Restart kubelet
  service:
    name: kubelet
    state: restarted
